// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Routine.Data;

namespace Routine.Migrations
{
    [DbContext(typeof(RoutineDbContext))]
    [Migration("20210209092324_UpdateEmployees")]
    partial class UpdateEmployees
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Routine.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d502f792-b007-4262-823e-26abd4666dce"),
                            Introduction = "Great Company",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = new Guid("9babffca-c2aa-4ff6-a4ee-0a22682d239e"),
                            Introduction = "Don't be evil",
                            Name = "Google"
                        },
                        new
                        {
                            Id = new Guid("29e02aef-3144-4f2a-ad19-4499a2732955"),
                            Introduction = "Fubao Company",
                            Name = "Alipapa"
                        });
                });

            modelBuilder.Entity("Routine.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e996af1-654e-4a07-9d38-0e1b0a1ab8cc"),
                            CompanyId = new Guid("d502f792-b007-4262-823e-26abd4666dce"),
                            DateOfBirth = new DateTime(1976, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "MSFT231",
                            FirstName = "Nick",
                            Gender = 1,
                            lastName = "Carton"
                        },
                        new
                        {
                            Id = new Guid("e0dae939-4275-4df9-95d5-317b72ae4526"),
                            CompanyId = new Guid("d502f792-b007-4262-823e-26abd4666dce"),
                            DateOfBirth = new DateTime(1981, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "MSFT235",
                            FirstName = "Vince",
                            Gender = 1,
                            lastName = "Carter"
                        },
                        new
                        {
                            Id = new Guid("c83404ff-c8a4-45a9-8f89-ce727a70f080"),
                            CompanyId = new Guid("9babffca-c2aa-4ff6-a4ee-0a22682d239e"),
                            DateOfBirth = new DateTime(1991, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "Gole167",
                            FirstName = "Fred",
                            Gender = 1,
                            lastName = "Huang"
                        });
                });

            modelBuilder.Entity("Routine.Entities.Employee", b =>
                {
                    b.HasOne("Routine.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Routine.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
